name: allewellyn4fanpage0
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.4
  font_awesome_flutter: ^9.0.0
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  
